apiVersion: v1
kind: Service
metadata:
  name: sample-file-api-service
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: TCP
      port: 8888
      targetPort: 80
  selector:
    app: sample-file-api
